# Sentry Values
# Configuration for Sentry deployment

user:
  email: admin@ckempire.local
  password: admin123

email:
  host: smtp.gmail.com
  port: 587
  username: sentry@ckempire.local
  password: password
  use_tls: true

web:
  replicas: 2
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

worker:
  replicas: 2
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

cron:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

postgresql:
  enabled: true
  postgresqlPassword: sentry123
  persistence:
    enabled: true
    size: 20Gi

redis:
  enabled: true
  auth:
    enabled: true
    password: sentry123

filestore:
  backend: "gcs"
  gcs:
    bucket: "ckempire-sentry-files"
    credentials: ""

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: sentry.ckempire.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: sentry-tls
      hosts:
        - sentry.ckempire.local 